// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QfFwA9D0i8VoEAkqrvaLD1UkVrrbam0',
    appId: '1:51838544354:web:6336111e803e903f83f1bb',
    messagingSenderId: '51838544354',
    projectId: 'alumnsapp',
    authDomain: 'alumnsapp.firebaseapp.com',
    storageBucket: 'alumnsapp.firebasestorage.app',
    measurementId: 'G-1MQDP8XFWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwPbOqfCqpOwEZP7-mDppFq0w6jsj4Ss',
    appId: '1:991683120258:android:e0a4c8f0112140735bf89b',
    messagingSenderId: '991683120258',
    projectId: 'alumns-app',
    storageBucket: 'alumns-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsdnr9vL7oHCBDwwD6NJOFw4TN3wIOnE',
    appId: '1:51838544354:ios:05792cc24935c72d83f1bb',
    messagingSenderId: '51838544354',
    projectId: 'alumnsapp',
    storageBucket: 'alumnsapp.firebasestorage.app',
    iosBundleId: 'com.example.alumnsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTsdnr9vL7oHCBDwwD6NJOFw4TN3wIOnE',
    appId: '1:51838544354:ios:05792cc24935c72d83f1bb',
    messagingSenderId: '51838544354',
    projectId: 'alumnsapp',
    storageBucket: 'alumnsapp.firebasestorage.app',
    iosBundleId: 'com.example.alumnsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-QfFwA9D0i8VoEAkqrvaLD1UkVrrbam0',
    appId: '1:51838544354:web:935de12f885a5ccd83f1bb',
    messagingSenderId: '51838544354',
    projectId: 'alumnsapp',
    authDomain: 'alumnsapp.firebaseapp.com',
    storageBucket: 'alumnsapp.firebasestorage.app',
    measurementId: 'G-H4EF8KQ9CJ',
  );
}